---
title: "**STOR 320: Introduction to Data Science**"
output:
  html_document:
    theme: cosmo
    toc: yes
    toc_float: yes
---


This course is an application-driven introduction to data science. Statistical and computational tools are valued throughout the modern workplace from Silicon Valley startups, to marine biology labs, to Wall Street firms. These tools require technical skills such as programming and statistics. They also require professional skills such as communication, teamwork, problem solving, and critical thinking.


- Instructor: [Robin Cunningham](http://stat-or.unc.edu/people/faculty/robin-cunningham)

- Instructional Assistant: [Adam Waterbury](http://stat-or.unc.edu/people/graduate-students-department)

- Graduate Research Consultant: [Varun Goel](https://varungoel.web.unc.edu/)

See the **[course syllabus](https://drive.google.com/open?id=0B2lwGKhIFjYYYVh5NVVsZVJjbmM)** for more information. 

# **Course Material**


| Date | Lecture | Slides | Notes & HW |
|------|---------|-------|-------|
|August 23 |Course Overview, Install R | [Lecture 1](https://www.dropbox.com/s/onli0k3vl1v6bmu/STOR%20320%20Lecture%201%2008-23-17.pptx?dl=0) | [R Downloads](http://rpubs.com/redrobincl/299923)|
|August 25 |Visualization and ggplot2 | [Lecture 2](https://www.dropbox.com/s/3kewdkom4r7ht5e/STOR%20320%20Lecture%202%2008-25-17.pptx?dl=0) | [Homework 1](http://rpubs.com/redrobincl/301780)|
|August 28 | ggplot Wrap-up and Workflow Basics| [Lecture 3](https://www.dropbox.com/s/403yr1vxniw7ave/STOR%20320%20Lecture%203%2008-28-17.pptx?dl=0) | [Reading for 8-28](http://rpubs.com/redrobincl/302494)|
|August 30 | Data Transformations with Dplyr| [Lecture 4](https://www.dropbox.com/s/2so7c7nr4pc9cwb/STOR%20320%20Lecture%204%2008-30-17.pptx?dl=0) | [Homework for 8-30](http://rpubs.com/redrobincl/302710)|
|Sept. 1 | Data Transformations with Dplyr| [Class Activity](https://www.dropbox.com/s/knonga5b5dzlu0h/STOR%20320%20%E2%80%93%20Class%20Activity%20090117.docx?dl=0) | [Homework for Sept 1](http://rpubs.com/redrobincl/303670)|
|Sept. 6 | Data Transformations with Dplyr| [Still Lecture 4 ](https://www.dropbox.com/s/2so7c7nr4pc9cwb/STOR%20320%20Lecture%204%2008-30-17.pptx?dl=0) | [Homework for Sept 6](http://rpubs.com/redrobincl/303670)|
|Sept. 8 | Workflow - Scripts, RMarkdown| [Lecture 5 ](https://www.dropbox.com/s/qzprzcyllm481mz/STOR%20320%20Lecture%204%2008-30-17.pptx?dl=0) | [Data Analysis 1](http://rpubs.com/redrobincl/305377)|
|Sept. 11 | Exploratory Data Analysis| [Lecture 6 ](https://www.dropbox.com/s/6vjlvmvi39v79oj/STOR%20320%20Lecture%206%2009-14-17.pptx?dl=0) | |
|Sept. 13 | Exploratory Data Analysis| [Lecture 7 ](https://www.dropbox.com/s/wmvimtcx3y35l8k/STOR%20320%20Lecture%207%2009-13-17.pptx?dl=0) |[Homework](http://rpubs.com/redrobincl/307274) |
|Sept. 15 | Tibbles and R Projects| [Class Activity ](http://rpubs.com/redrobincl/307978) |[Activity as .rmd](https://www.dropbox.com/s/h5huqubm36052bo/September%2015%20Class%20activity.Rmd?dl=0) |
|Sept. 18 | Importing Data| [Lecture 9 ](https://www.dropbox.com/s/gsscenxrw4ken4c/STOR%20320%20Lecture%209%2009-18-17.pptx?dl=0) |[heights.csv](https://www.dropbox.com/s/bjvbfman7i7qhu2/heights.csv?dl=0) |
|Sept. 20 | Tidy Data| [Lecture 10 ](https://www.dropbox.com/s/hqjoiosey01jibs/STOR%20320%20Lecture%2010%2009-20-17.pptx?dl=0) |[MOMA_art.csv](https://drive.google.com/open?id=0B2lwGKhIFjYYb0NMSF92dTVGQ3c)  [MOMA_artists.csv](https://drive.google.com/open?id=0B2lwGKhIFjYYRktDeWtvWHcta3M) |





- the datasets use in the class are on [data.world](https://data.world/iain/stor-390/) and [github](https://github.com/idc9/stor390/tree/master/data/)

- all of the course material is on the [github repo](https://github.com/idc9/stor390) including
    - [.Rmd files](https://github.com/idc9/stor390/tree/master/notes/) for the notes 
    - [example code](https://github.com/idc9/stor390/tree/master/example_code/) are also on github


- most of the course material is in the lecture notes (linked to above) and reading. 



# **Reading**

Readings should be complete by the following class. There are two (free) primary references:

- [R for Data Science](http://r4ds.had.co.nz/) (r4ds)
- [R Programming for Data Science](https://leanpub.com/rprogramming) (RPDS)

**August 22**

- Work through [getting started notes](http://rpubs.com/redrobincl/299923). We will discuss it as necessary at our next meeting, but you should have R and Rstudio installed and have attempted to run the code in this document.
- Read before next class: [The Introduction to R4DS](http://r4ds.had.co.nz/introduction.html)

# **Additional resources**

# **Miscellaneous**

This course was made possible by a grant from the [Data@Carolina](http://data.web.unc.edu/) initiative and a ton of [**input from lots of very smart people**](https://docs.google.com/document/d/1EAIiex92oKphCeBAtmJ9NOyKti76QDsC5lz7vbL7Gwo/edit).

This page was last updated on `r Sys.time()` Eastern Time.
